POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "type": "HealthCheck",
    "description": "great whatever",
    "date": "2012-11-11",
    "specialist": "mr matkha",
    "healthCheckRating": 1
}