POST http://localhost:4000/api/blogs
Content-Type: application/json

{
    "title": "User Authenticated Blog",
    "author": "nikita",
    "url": "nikita.com",
    "likes": 19,
    "userId": "637296d01b6827e2524735a5"
}